name: Optimize Wedding Images

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  optimize-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Optimize images with calibreapp
        uses: calibreapp/image-actions@v1
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          jpegQuality: '80'
          pngQuality: '80'
